Repository cloudradar-monitoring/cagent, pull requests merged in 2018-11, with the labels that each got.

#22 fix typo in filename x68 -> x86
  .circleci/config.yml
Labels: bug

#26 Configure golangci
  .circleci/config.yml
  .golangci.yml
Labels: enhancement

#27 Fix regex to properly detect rc versions by tag
  .circleci/config.yml
Labels: bug, enhancement

#25 Set default log level to error
  cmd/cagent/main.go
  config.go
Labels: enhancement

#7 Report most cpu consuming process
  Gopkg.lock
  Gopkg.toml
  perfcounters/performance_query.go
  perfcounters/win_perf_counters.go
  pkg/monitoring/top/top.go
  pkg/monitoring/top/top_nonwindows.go
  pkg/monitoring/top/top_windows.go
  vendor/github.com/lxn/win/AUTHORS
  vendor/github.com/lxn/win/LICENSE
  vendor/github.com/lxn/win/README.mdown
  vendor/github.com/lxn/win/advapi32.go
  vendor/github.com/lxn/win/combobox.go
  vendor/github.com/lxn/win/comctl32.go
  vendor/github.com/lxn/win/comdlg32.go
  vendor/github.com/lxn/win/datetimepicker.go
  vendor/github.com/lxn/win/edit.go
  vendor/github.com/lxn/win/gdi32.go
  vendor/github.com/lxn/win/gdiplus.go
  vendor/github.com/lxn/win/header.go
  vendor/github.com/lxn/win/kernel32.go
  vendor/github.com/lxn/win/listbox.go
  vendor/github.com/lxn/win/listview.go
  vendor/github.com/lxn/win/menu.go
  vendor/github.com/lxn/win/ole32.go
  vendor/github.com/lxn/win/oleaut32.go
  vendor/github.com/lxn/win/oleaut32_386.go
  vendor/github.com/lxn/win/oleaut32_amd64.go
  vendor/github.com/lxn/win/opengl32.go
  vendor/github.com/lxn/win/pdh.go
  vendor/github.com/lxn/win/shdocvw.go
  vendor/github.com/lxn/win/shell32.go
  vendor/github.com/lxn/win/shobj.go
  vendor/github.com/lxn/win/shobj_386.go
  vendor/github.com/lxn/win/shobj_amd64.go
  vendor/github.com/lxn/win/statusbar.go
  vendor/github.com/lxn/win/syslink.go
  vendor/github.com/lxn/win/tab.go
  vendor/github.com/lxn/win/toolbar.go
  vendor/github.com/lxn/win/tooltip.go
  vendor/github.com/lxn/win/treeview.go
  vendor/github.com/lxn/win/updown.go
  vendor/github.com/lxn/win/user32.go
  vendor/github.com/lxn/win/uxtheme.go
  vendor/github.com/lxn/win/win.go
  vendor/github.com/lxn/win/winspool.go
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
Labels: enhancement

#32 set to default log level is the user has provded an invalid value
  cmd/cagent/main.go
Labels: bug

#36 refactor handler.go
  cmd/cagent/main.go
  config.go
  cpu.go
  fs.go
  handler.go
  network.go
  windows.go
  windows_fallback.go
Labels: codestyle

#39 use proper windows paths
  build-win.bat
Labels: bug

#37 [cagent & frontman] rework default config
  .gitignore
  Gopkg.lock
  Gopkg.toml
  cmd/cagent/main.go
  config.go
  log.go
  vendor/github.com/BurntSushi/toml/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
  vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING
  vendor/github.com/troian/toml/.gitignore
  vendor/github.com/troian/toml/.travis.yml
  vendor/github.com/troian/toml/COMPATIBLE
  vendor/github.com/troian/toml/COPYING
  vendor/github.com/troian/toml/Makefile
  vendor/github.com/troian/toml/README.md
  vendor/github.com/troian/toml/cmd/toml-test-decoder/COPYING
  vendor/github.com/troian/toml/cmd/toml-test-encoder/COPYING
  vendor/github.com/troian/toml/cmd/tomlv/COPYING
  vendor/github.com/troian/toml/decode.go
  vendor/github.com/troian/toml/decode_meta.go
  vendor/github.com/troian/toml/doc.go
  vendor/github.com/troian/toml/encode.go
  vendor/github.com/troian/toml/encoding_types.go
  vendor/github.com/troian/toml/encoding_types_1.1.go
  vendor/github.com/troian/toml/lex.go
  vendor/github.com/troian/toml/parse.go
  vendor/github.com/troian/toml/session.vim
  vendor/github.com/troian/toml/type_check.go
  vendor/github.com/troian/toml/type_fields.go
Labels: enhancement
