Repository cloudradar-monitoring/cagent, pull requests merged in 2018-12, with the labels that each got.

#41 Separate configuration and functionality
  cagent.go
  cmd/cagent/main.go
  config.go
  cpu.go
  fs.go
  handler.go
  log.go
  network.go
  system.go
  windows.go
Labels: enhancement

#40 remove SetVersion and pass version as argument to New
  cagent.go
  cmd/cagent/main.go
Labels: codestyle

#44 refactor main.go
  cagent.go
  cmd/cagent/main.go
  config.go
  cpu.go
  fs.go
  handler.go
  log.go
  network.go
  system.go
  windows.go
Labels: codestyle

#45 Cherry-pick of https://github.com/go-ole/go-ole/pull/180
  vendor/github.com/go-ole/go-ole/safearray_windows.go
  vendor/github.com/go-ole/go-ole/safearrayconversion.go
Labels: bug

#47 update go-ole to v1.2.2
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/go-ole/go-ole/README.md
  vendor/github.com/go-ole/go-ole/com.go
  vendor/github.com/go-ole/go-ole/com_func.go
  vendor/github.com/go-ole/go-ole/idispatch_windows.go
  vendor/github.com/go-ole/go-ole/safearray_func.go
  vendor/github.com/go-ole/go-ole/variant.go
  vendor/github.com/go-ole/go-ole/variant_date_386.go
  vendor/github.com/go-ole/go-ole/variant_date_amd64.go
  vendor/github.com/go-ole/go-ole/variant_ppc64le.go
Labels: enhancement

#50 fix file output mode
  cmd/cagent/main.go
  handler.go
Labels: bug

#49 migrate to new signing machine
  .circleci/config.yml
  build-win.bat
Labels: enhancement

#46 List hyperv vms
  cagent.go
  config.go
  handler.go
  mem_windows.go
  perfcounters/win_perf_counters.go
  pkg/monitoring/top/top.go
  pkg/monitoring/top/top_nonwindows.go
  pkg/monitoring/top/top_windows.go
  pkg/monitoring/vmstat/hyperv/hyperv_wmi.go
  pkg/monitoring/vmstat/hyperv/provider_windows.go
  pkg/monitoring/vmstat/vmstat.go
  pkg/monitoring/watcher_windows.go
  pkg/wmi/wmi.go
  virt_nonwindows.go
  virt_windows.go
Labels: enhancement
