Repository cloudradar-monitoring/cagent, pull requests merged in 2019-02, with the labels that each got.

#61 Service control with flags
  cagent.go
  cmd/cagent/main.go
  log.go
Labels: enhancement

#88 dep: update dmidecode to 0.0.3
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/cloudradar-monitoring/dmidecode/LICENSE
  vendor/github.com/cloudradar-monitoring/dmidecode/dmidecode.go
  vendor/github.com/cloudradar-monitoring/dmidecode/types.go
Labels: enhancement

#91 fix: hwinventory do not fail if DMI type not found
  Gopkg.lock
  Gopkg.toml
  pkg/hwinfo/hwinfo_nonwindows.go
  vendor/github.com/cloudradar-monitoring/dmidecode/dmidecode.go
  vendor/github.com/cloudradar-monitoring/dmidecode/types.go
Labels: enhancement

#93 fix instruction for build from sources
  README.md
Labels: bug

#95 Fix var name
  pkg/monitoring/vmstat/hyperv/hyperv_wmi.go
Labels: bug

#84 Improve CI
  .circleci/config.yml
  Makefile
Labels: bug, enhancement

#96 Save minconfig on windows
  cmd/cagent/winui.go
  config.go
Labels: enhancement

#101 fix: improve error handling in hwinfo for windows
  pkg/hwinfo/hwinfo_windows.go
Labels: enhancement
