Repository cloudradar-monitoring/cagent, pull requests merged in 2019-01, with the labels that each got.

#58 decode and post hardware inventory
  .goreleaser.yml
  Gopkg.lock
  Gopkg.toml
  cagent.go
  config.go
  handler.go
  pkg-scripts/cagent-dmidecode
  pkg/hwinfo/hwinfo.go
  pkg/hwinfo/hwinfo_nonwindows.go
  pkg/hwinfo/hwinfo_windows.go
  pkg/wmi/wmi.go
  types.go
  vendor/github.com/cloudradar-monitoring/dmidecode/.gitignore
  vendor/github.com/cloudradar-monitoring/dmidecode/LICENSE
  vendor/github.com/cloudradar-monitoring/dmidecode/README.md
  vendor/github.com/cloudradar-monitoring/dmidecode/dmidecode.go
  vendor/github.com/cloudradar-monitoring/dmidecode/types.go
Labels: enhancement

#59 Add Makefile extract some ci tasks to it and bump build image
  .circleci/config.yml
  .gitignore
  Makefile
Labels: enhancement

#71 Fix top
  cagent.go
  cmd/cagent/main.go
  config.go
  handler.go
  pkg/monitoring/top/top.go
  pkg/monitoring/top/top_nonwindows.go
  pkg/monitoring/top/top_windows.go
Labels: enhancement

#74 ignore failed processes, if we log the errors we get way too many errors
  pkg/monitoring/top/top_nonwindows.go
Labels: bug

#75 WIP: More top fixes for process monitoring
  cagent.go
  handler.go
  pkg/monitoring/top/top.go
Labels: bug, enhancement
