Repository cloudradar-monitoring/cagent, pull requests merged in 2019-04, with the labels that each got.

#125 Add aptly integration
  .circleci/config.yml
  Makefile
Labels: enhancement

#130 Fix incorrect WMI (WBEM) server connection args
  pkg/monitoring/sensors/temperature_windows.go
Labels: do not merge

#131 Fix potential panic when listing upstart services
  pkg/monitoring/services/services_nonwindows.go
Labels: bug

#132 Deb and fpm fixes
  .goreleaser.yml
Labels: enhancement

#133 Fix panic after unsuccessful attempt to gather process memory usage info
  processes_notwindows.go
Labels: bug

#134 fix: run dmidecode without sudo on Darwin
  pkg/hwinfo/hwinfo_darwin.go
  pkg/hwinfo/hwinfo_nonwindows.go
  pkg/hwinfo/hwinfo_other.go
Labels: bug

#136 feat: allocate MeasurementsMap to package
  cpu.go
  cpu_utilisation_analyser.go
  fs.go
  handler.go
  mem.go
  mem_windows.go
  network.go
  pkg/common/types.go
  ports.go
  processes.go
  raid.go
  raid_test.go
  swap.go
  system.go
  types.go
  windows.go
  windows_fallback.go
Labels: enhancement

#138 Pass container id to docker inspect
  pkg/monitoring/docker/docker.go
Labels: bug

#135 feat: S.M.A.R.T control
  .goreleaser.yml
  README.md
  SMART.md
  cagent.go
  config.go
  handler.go
  pkg-scripts/cagent-smartctl
  pkg/smart/check_required_tools_darwin.go
  pkg/smart/check_required_tools_linux.go
  pkg/smart/check_required_tools_windows.go
  pkg/smart/detect_disks_darwin.go
  pkg/smart/detect_disks_nix.go
  pkg/smart/detect_disks_windows.go
  pkg/smart/parse.go
  pkg/smart/parse_disk.go
  pkg/smart/parse_disk_test.go
  pkg/smart/smartctl_prepare_notwindows.go
  pkg/smart/smartctl_prepare_windows.go
  pkg/smart/smartctl_version_test.go
  pkg/smart/types.go
Labels: enhancement
